name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every Midnight Daily 
  workflow_dispatch:      # Allows manual trigger

permissions:
  contents: write        # Needed for pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Create .gitignore if not exists
        run: |
          if [ ! -f .gitignore ]; then
            echo "node_modules/" > .gitignore
            echo "*.log" >> .gitignore
          fi

      - name: Install dependencies
        run: |
          npm clean-install
          
      - name: Run GitHub Stats Script
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          node stats.js

      - name: Check for README changes
        id: check_changes
        run: |
          git diff --exit-code README.md || echo "changes=true" >> $GITHUB_OUTPUT

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README stats"
          git push