name: Update README with GitHub Stats

on:
  schedule:
    - cron: '40 14 * * *'  # Runs at 14:40 UTC daily
  workflow_dispatch:        # Allows manual trigger

permissions:
  contents: write          # Needed for pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4    # Updated to v4

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '18'
          cache: 'npm'              # Added caching for better performance

      - name: Install dependencies
        run: |
          npm ci                    # Using ci instead of install for clean installs

      - name: Run GitHub Stats Script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Using built-in token
        run: |
          node stats.js

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update README stats"
          git push