name: Update README with GitHub Stats

on:
  schedule:
    - cron: '0 23 * * *'  # Runs every 7 am daily UTC +8
  workflow_dispatch:        # Allows manual trigger

permissions:
  contents: write          # Needed for pushing changes

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Create gitignore
        run: |
          echo "node_modules/" > .gitignore
          echo "package-lock.json" >> .gitignore

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Restore GitHub Cache
        uses: actions/cache@v3
        with:
          path: github_cache.json
          key: github-stats-cache-${{ github.repository }}-${{ hashFiles('stats.js') }}
          restore-keys: |
            github-stats-cache-${{ github.repository }}-

      - name: Install dependencies
        run: |
          npm ci

      - name: Run GitHub Stats Script
        env:
          PERSONAL_GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        run: |
          node stats.js

      - name: Save GitHub Cache
        uses: actions/cache/save@v3
        if: always()
        with:
          path: github_cache.json
          key: github-stats-cache-${{ github.repository }}-${{ hashFiles('stats.js') }}-${{ github.run_id }}

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -f README.md
          git commit -m "Update README stats" || echo "No changes to commit"
          git push origin HEAD || echo "No changes to push"
